name: "Build"

on:
  pull_request:
    paths:
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/build_wheels.yml"
      - ".gitmodules"
      - "clp_ffi_py/**"
      - "lint-tasks.yml"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "README.md"
      - "requirements-build.txt"
      - "requirements-dev.txt"
      - "setup.cfg"
      - "setup.py"
      - "src/**"
      - "Taskfile.yml"
      - "tests/**"
      - ".yamllint.yml"
  push:
    paths:
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/build_wheels.yml"
      - ".gitmodules"
      - "clp_ffi_py/**"
      - "lint-tasks.yml"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "README.md"
      - "requirements-build.txt"
      - "requirements-dev.txt"
      - "setup.cfg"
      - "setup.py"
      - "src/**"
      - "Taskfile.yml"
      - "tests/**"
      - ".yamllint.yml"

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  linters:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli"

      - name: "Run lint task"
        shell: "bash"
        run: "task lint:check"

  build_wheels:
    needs: ["linters"]
    name: "Build wheels on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12"]

    steps:
      - uses: "actions/checkout@v3"

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Set up QEMU"
        if: "runner.os == 'Linux'"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "all"

      - name: "Build wheels"
        uses: "pypa/cibuildwheel@v2.16.2"
        env:
          CIBW_ARCHS_LINUX: "auto aarch64"
          MACOSX_DEPLOYMENT_TARGET: "10.15"

      - uses: "actions/upload-artifact@v3"
        with:
          name: "wheel-${{ matrix.os }}"
          path: "./wheelhouse/*.whl"
